Changing the README, adding a Contribution Guide and a Code of Conduct
mediathekview/MediathekView pull request #556
Opened 2020-10-02 18:22 UTC by Nicklas2751

I changed the README a bit and created a Contribution Guide and also a Code of Conduct

2020-10-07 17:56 UTC, pidoubleyou approved these changes

2020-10-08 05:25 UTC, derreisende77 commented
Wie schon abseits beschrieben stehe ich dem ganzen hier sehr kritisch gegenüber und halte es für nicht notwendig. Wir müssen nicht Lemming spielen nur weil die anderen es gerade voll toll finden.

2020-10-08 05:27 UTC, derreisende77 requested changes
Ich bin gegen den CoC wie schon abseits besprochen.

2020-10-25 12:09 UTC, Nicklas2751 commented
@derreisende77 Ich habe den CoC entfernt. ;)

2020-10-25 16:43 UTC, derreisende77 approved these changes

2021-01-29 08:50 UTC, merged